server:
  port: 9002
management:
  security:
    enabled: false
spring:
  application:
    name: bus-service
  rabbitmq:
     host: 127.0.0.1
     port: 5672
     username: rabbitmq
     password: rabbitmq

#####################################################################################################
# eurake
eureka:
  instance:
      #表示eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance
      prefer-ip-address: true
      #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
      lease-renewal-interval-in-seconds: 5
      #续约到期时间（默认90秒）
      lease-expiration-duration-in-seconds: 10
  client:
    service-url:
     defaultZone: http://localhost:2188/eureka

#####################################################################################################

# 打印日志 trace
logging:
  level:
    root: info
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.springms: DEBUG
#####################################################################################################

testbus : 11111