server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native #native访问本地配置 dev 打开git配置
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/local
#        git:
#          uri: https://github.com/itwmang/springCloudConfig
#          search-paths: mac-dev
#          username: itfast@yeah.net
#          password: itfast123.
    bus:
      trace:
        enabled: true
  rabbitmq:
     host: 127.0.0.1
     port: 5672
     username: rabbitmq
     password: rabbitmq
  security:
    user:
      name: configcenter
      password: config0510

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #表示eureka client发送心跳给server端的频率。如果  在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance
    lease-renewal-interval-in-seconds: 5 #注册服务默认心跳时间为30秒，当一个服务器不可用，需要3个心跳才能让服务器和客户端的元数据相同。生产环境最好使用默认配置。
    #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
    lease-expiration-duration-in-seconds: 10 # 续约到期时间（默认90秒）
  client:
    healthcheck:
      enable: true # 开启健康检查（依赖spring-boot-starter-actuator）
    service-url:
      defaultZone: http://eureka:eureka0510@localhost:2188/eureka
      #开启密码模式 http://${userName}:${password}@localhost:2180/eureka
    registry-fetch-interval-seconds: 10
