server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/itwmang/springCloudConfig
          search-paths: mac-dev
          username: itfast@yeah.net
          password: itfast123.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2188/eureka